---
title: "Gold_Sivler_Model"
author: "JDRK"
date: "2024-09-19"
output:
  html_document:
    theme: flatly
    toc: yes
    toc_float: 
       collapses: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE,message=FALSE,warning=FALSE}

library(
  pacman)

library(hrbrthemes)
library(prettydoc)

p_load("forecast","tseries","quantmod", "ggplot2","GGally","gt","plotly",
       "DT","stringr","tibble","tidyr","lubridate","dplyr","formattable","data.table","scales","gmodels","openxlsx","readxl","janitor")

 setwd("/home/jmachiine/Documents/GitHub/AFAAQITC-Report/Gold_Silver_Model/")

 
gl<-read.csv("gold.csv")

gl<-
gl %>% select(c(1,5)) %>% 
rename(price=High) %>% mutate(Date=mdy(Date)) %>% 
mutate(mn=round_date(Date,"month"))%>%
mutate(qurerters=quarters(Date),monthn=month(Date),months=format(Date,"%b"))





mn<-gl %>% group_by(mn) %>% summarize(price=mean(price))



mn_rts<-ts(mn$price,start = c(2014,10),c(2024,10),frequency = 12)

mn_rets<-ets(mn_rts)

mn_rfor<-forecast(mn_rets,h = 14)

mn_rar<-auto.arima(mn_rts)
mn_rarfor<-forecast(mn_rar,h = 12)


#Model

model<-cbind(
data.frame(Date= seq(as.Date("2024-11-01"),len=14,by="month"))
,rownames_to_column(data.frame(mn_rfor)) %>% select(c(4,6)))


model_chart<-
model %>% 
mutate(Date=as.POSIXct(Date)) %>% 
pivot_longer(!Date,names_to = "Levels",values_to = "Prices") %>% 
ggplot(aes(x=Date,y=Prices,color=Levels,group=Levels))+
geom_line(size=1)+geom_point(color="black",size=1)+
scale_color_manual(values = c("#d35400","#16a085"))+
labs(x="",y="",title = "Gold Forecast Model Next 14 Month",
subtitle ="Focus Data Period: Oct 2014 - Sep 2024" )+
scale_y_continuous(labels = comma)+theme_bw()+
scale_x_datetime(date_breaks = "month",date_labels = "%b%y")+
theme(axis.text.x = element_text(face = "bold",colour = "black",size = 10),
axis.text.y = element_text(face = "bold",colour = "black",size = 10),
title = element_text(face = "bold",colour = "#2c3e50"))
  
  
model_tbl<-
model %>% gt() %>% tab_header(title = "Gold Forecast Arima Model ",
subtitle = "Focus Data Period : Oct 2014 - Sep 2024") %>% 
cols_label_with(columns =everything() ,fn = toupper) %>% 
tab_row_group(rows = Date>= "2025-01-01",label = "2025",id = "2025",group = "2025") %>% 
tab_row_group(rows = Date< "2025-01-01",label = "2024",id = "2024",group = "2024") %>% 
fmt_number(columns = c(2,3),decimals = 2) %>% fmt_date(columns = 1,date_style = "yMMM") %>% 
summary_rows(groups = c("2024","2025"),columns = c(2,3),fns =list(Average=~mean(.))) %>% 
tab_style(style =list(cell_fill("#A0937D"),cell_text(weight = "bold",align = "center",color="white")) ,locations = cells_title()) %>% 
tab_style(style =list(cell_fill("#E7D4B5"),cell_text(weight = "bold",align = "center")) ,locations=cells_column_labels()) %>% 
tab_style(style =list(cell_fill("#E7D4B5"),cell_text(weight = "bold",align = "center")) ,locations=cells_stubhead()) %>% 
tab_style(style =list(cell_fill("#F6E6CB"),cell_text(weight = "bold",align = "center")) ,
locations=cells_stub_summary()) %>% 
tab_style(style =list(cell_fill("#F6E6CB"),cell_text(weight = "bold",align = "center")) ,
locations=cells_summary()) %>% 
tab_style(style =list(cell_fill("#F1F1F1"),cell_text(weight = "bold")) ,
locations=cells_row_groups()) %>% 
tab_style(style =list(cell_text(weight = "bold",align = "center",color="#967E76")) ,
locations=cells_body())



sl<-read.csv(file = "silver.csv") %>% select(c(1,2))

sl<-
sl %>%mutate(Date=mdy(Date)) %>%
mutate(mn=round_date(Date,"month"),QR=quarters(Date),
monthn=month(Date),months=format(Date,"%b"))


sl_mn<-sl %>% group_by(mn) %>% summarize(price=mean(Price)) 

sl_ts<-ts(sl_mn$price,start = c(2010,1),end = c(2023,12),frequency = 12)

sl_ets<-ets(sl_ts)

sl_for<-forecast(sl_ets,h = 10)


sl_last<-
cbind(
  sl_mn[c(169:178),],
rownames_to_column(data.frame(sl_for)) %>% select(c(4,6))
)

silver_detect_chart<-
sl_last %>% 
pivot_longer(!mn,names_to = "levels",values_to = "prices") %>% 
mutate(mn=as.POSIXct(mn)) %>% 
ggplot(aes(x=mn,y=prices,color=levels,group=levels))+
geom_line(size=1)+geom_point()+scale_color_manual(values =  c("#30336b","#6ab04c","#eb4d4b"))+
labs(x="",y="",title = "Silver Detect Last 10 Months Prices Model")+
theme_classic()+theme(axis.text.x = element_text(colour = "black",face = "bold"),
                      axis.text.y = element_text(colour = "black",face = "bold"))+scale_x_datetime(date_breaks = "month",date_labels = "%B")


silver_detect_tbl<-
sl_last %>%rename(date=mn) %>% mutate(var80=round(Hi.80/price,3)-1,var95=round(Hi.95/price,3)-1)%>% 
gt() %>% fmt_number(columns = c(2:4),decimals = 2)  %>% 
cols_label_with(columns =everything() ,fn = toupper) %>% 
tab_header(title = "Detect Last 10 Months Model",subtitle = "Focus Data Period: Jan 2010 - Dec 2023") %>% 
fmt_date(date_style ="yMMM" ,columns = 1) %>% 
fmt_percent(columns = c(5,6),decimals = 2) %>% 
  tab_style(style =list(cell_fill("#A0937D"),cell_text(weight = "bold",align = "center",color="white")) ,locations = cells_title()) %>% 
tab_style(style =list(cell_fill("#E7D4B5"),cell_text(weight = "bold",align = "center")) ,locations=cells_column_labels()) %>% 
tab_style(style =list(cell_text(color="#7f8c8d",weight = "bold",align = "center")) ,locations=cells_body())




mn_slts<-ts(sl_mn$price,start =c(2010,1) ,end =c(2024,10) ,frequency = 12)
mn_slets<-ets(mn_slts)
mn_slforets<-forecast(mn_slets,h = 14)
mn_slar<-auto.arima(mn_slts)
mn_slfar<-forecast(mn_slar,h = 14)


silver_Model_Chart<- 
cbind(
data.frame(mn=seq(as.Date("2024-11-01"),len=14,by="month"))
,
rownames_to_column(data.frame(mn_slfar)) %>% select(c(4,6))
) %>% 
rename(date=mn) %>% mutate(date=as.POSIXct(date)) %>% pivot_longer(!date,names_to ="levels" ,values_to = "price") %>% 
ggplot(aes(x=date,y=price,color=levels,group =levels))+geom_line(size=1.2)+
geom_point(color="black") +scale_color_manual(values = c("#6ab04c","#eb4d4b","#30336b"))+
scale_x_datetime(date_breaks ="month" ,date_labels = "%b%Y")+labs(x="",y="",title = "Silver Forecast Next 14 Months")+scale_y_continuous(limits = c(33,43))+
theme_bw()+theme(axis.text.x = element_text(colour = "black",face = "bold"),
axis.text.y = element_text(colour = "black",face = "bold"),title = element_text(colour = "#30336b",face = "bold"))


silver_Model_tbl<-
cbind(
data.frame(mn=seq(as.Date("2024-11-01"),len=14,by="month"))
,
rownames_to_column(data.frame(mn_slfar)) %>% select(c(4,6))) %>% 
rename(date=mn) %>% mutate(var=round(Hi.95/Hi.80,2)-1) %>% gt()%>% fmt_number(columns = c(2:4),decimals = 2)  %>% 
  cols_label_with(columns =everything() ,fn = toupper) %>% 
  tab_header(title = "Detect Last 10 Months Model",subtitle = "Focus Data Period: Jan 2010 - Dec 2023") %>% 
  fmt_date(date_style ="yMMM" ,columns = 1) %>% 
  fmt_percent(columns = 4,decimals = 2) %>% fmt_currency(columns = c(2,3),currency = "USD",decimals = 2)%>% 
  tab_style(style =list(cell_fill("#A0937D"),cell_text(weight = "bold",align = "center",color="white")) ,locations = cells_title()) %>% 
  tab_style(style =list(cell_fill("#E7D4B5"),cell_text(weight = "bold",align = "center")) ,locations=cells_column_labels()) %>% 
  tab_style(style =list(cell_text(color="#7f8c8d",weight = "bold",align = "center")) ,locations=cells_body())


```



### Gold Forecast Model
 

```{r echo=FALSE,warning=FALSE,message=FALSE}
ggplotly( model_chart,width=800)

```

 
```{r echo=FALSE,message=FALSE,warning=FALSE}
model_tbl
```



### Silver Last Detect Model

```{r echo=FALSE,message=FALSE,warning=FALSE}
autoplot(decompose(diff(sl_ts)))

```


```{r echo=FALSE,message=FALSE,warning=FALSE}
ggplotly( silver_detect_chart, width=800)
```


```{r warning=FALSE,message=FALSE,echo=FALSE}
silver_detect_tbl
```


### Silver Forecast Next 14 Months Model 

```{r echo=FALSE,message=FALSE,warning=FALSE}
ggplotly( silver_Model_Chart,width=800)
```


```{r message=FALSE,echo=FALSE,warning=FALSE}
silver_Model_tbl
```


